# Generated by Django 5.1.7 on 2026-03-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contacts_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='pet_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
