# Generated by Django 5.1.7 on 2026-03-16 13:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomType',
            new_name='ChatRoom',
        ),
        migrations.RenameModel(
            old_name='RoommParticipants',
            new_name='RoomParticipants',
        ),
    ]
