# Generated by Django 5.1.7 on 2026-03-21 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_messagestatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageStatus',
        ),
    ]
