# Generated by Django 5.1.7 on 2026-03-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_messages_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='messages',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
