# Generated by Django 5.1.7 on 2026-03-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_remove_messages_is_deleted_messages_is_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
