# Generated by Django 5.1.7 on 2026-03-29 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_messages_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='group_image/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='roomparticipants',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='chat.chatroom'),
        ),
    ]
