# Generated by Django 5.1.7 on 2026-03-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_chatroom_image_alter_roomparticipants_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/group_image/', verbose_name='Image'),
        ),
    ]
