# Generated by Django 5.1.7 on 2026-03-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_current_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
