# Generated by Django 5.1.7 on 2026-03-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_otpverification_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='attempt_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
