# Generated by Django 5.1.7 on 2026-03-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_otpverification_attempt_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='attempt_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
