# Generated by Django 5.1.7 on 2026-03-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_otpverification_attempt_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='resend_count',
            field=models.IntegerField(default=0),
        ),
    ]
