# Generated by Django 5.1.7 on 2026-03-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_otpverification_resend_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.CharField(default='Available', max_length=1000),
            preserve_default=False,
        ),
    ]
